# Generated by Django 4.2.4 on 2023-08-22 17:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_content_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_upload',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
