# Generated by Django 4.2.4 on 2023-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_content_upload_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreply',
            old_name='accepted',
            new_name='is_accepted',
        ),
        migrations.RenameField(
            model_name='postreply',
            old_name='comment_date',
            new_name='publication_date',
        ),
        migrations.AlterField(
            model_name='postreply',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
